"""Add ai_system_prompt to Course model

Revision ID: 0015_course_ai_prompt
Revises: 0010_lesson_fields
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015_course_ai_prompt'
down_revision = '0010_lesson_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('ai_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'ai_system_prompt')
    # ### end Alembic commands ###
